services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: bayrktlihn
      POSTGRES_USER: bayrktlihn
      POSTGRES_DB: bayrktlihn
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8090:8080
    environment:
      #      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: JJ8iWsBsS46d2hCP3yNpfw
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092
  kafka-1:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:29092,CONTROLLER://:29093,EXTERNAL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:29092,EXTERNAL://host.docker.internal:9092
      KAFKA_KRAFT_CLUSTER_ID: JJ8iWsBsS46d2hCP3yNpfw
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  kafka-2:
    image: bitnami/kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:29092,CONTROLLER://:29093,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092,EXTERNAL://host.docker.internal:9093
      KAFKA_KRAFT_CLUSTER_ID: JJ8iWsBsS46d2hCP3yNpfw
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  kafka-3:
    image: bitnami/kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:29092,CONTROLLER://:29093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:29092,EXTERNAL://host.docker.internal:9094
      KAFKA_KRAFT_CLUSTER_ID: JJ8iWsBsS46d2hCP3yNpfw
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT